In [4]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os
from IPython.display import display
pd.options.display.max_rows = 13

In [5]:
import re 


def cleanup(text):
    """
        Fun√ß√£o de limpeza muito simples que troca alguns sinais b√°sicos por espa√ßos
    """
    #import string
    punctuation = '[!-.:?;]' # Note que os sinais [] s√£o delimitadores de um conjunto.
    pattern = re.compile(punctuation)
    text_subbed = re.sub(pattern, ' ', text)
    return text_subbed

In [6]:
print('Esperamos trabalhar no diret√≥rio')
print(os.getcwd())

Esperamos trabalhar no diret√≥rio
C:\Users\guilh\Desktop\projeto1cdados

In [7]:
dados = pd.read_excel('NuBank.xlsx')
dados

                                           Treinamento  classifica√ß√£o
0    @jaum_lealf @cecbreno @nubank amigo que triste...              0
1    @oandrevinic aaaah, que not√≠cia boa!\n\nconta ...              0
2    quando o nubank vai liberar a minha fun√ß√£o cr√©...              0
3    @catundabruno @nubank eu vou cancelar. n√£o hou...              0
4            nubank aumentou meu limite, to fudida ü•∫üò≠üòÇ              0
..                                                 ...            ...
295  se tem uma coisa que eu amo √© meu cart√£o nuban...              0
296  rt @wjucollection: üå± itzy\n\nalbum it‚Äôz icy: f...              0
297                     aff meu nubank novo √© mt lindo              1
298  olhei o d√≥lar canadense hoje e t√° r$ 3,39 e ta...              0
299  @nubank o que custa me aceitar no cr√©dito? htt...              1

[300 rows x 2 columns]

In [8]:
dados.loc[:,'classifica√ß√£o'] = dados['classifica√ß√£o'].astype('category')
dados['classifica√ß√£o'].cat.categories = ["irrelevante", "relevante"]
dados

                                           Treinamento classifica√ß√£o
0    @jaum_lealf @cecbreno @nubank amigo que triste...   irrelevante
1    @oandrevinic aaaah, que not√≠cia boa!\n\nconta ...   irrelevante
2    quando o nubank vai liberar a minha fun√ß√£o cr√©...   irrelevante
3    @catundabruno @nubank eu vou cancelar. n√£o hou...   irrelevante
4            nubank aumentou meu limite, to fudida ü•∫üò≠üòÇ   irrelevante
..                                                 ...           ...
295  se tem uma coisa que eu amo √© meu cart√£o nuban...   irrelevante
296  rt @wjucollection: üå± itzy\n\nalbum it‚Äôz icy: f...   irrelevante
297                     aff meu nubank novo √© mt lindo     relevante
298  olhei o d√≥lar canadense hoje e t√° r$ 3,39 e ta...   irrelevante
299  @nubank o que custa me aceitar no cr√©dito? htt...     relevante

[300 rows x 2 columns]

In [9]:
re = dados["classifica√ß√£o"] == "relevante"
relevantes = dados.loc[re,["Treinamento"]].copy()
relevantes

                                           Treinamento
7    @rodrigo_rhr @nubank @bradesco aff, pistola es...
8            app da digo √© uma bosta, mil vezes nubank
11   @newspotgabs @nubank so queria que me dessem l...
12   @vitorswu @nubank @bradesco nossa direto os ca...
14              chegou o meu cart√£o da nubank aaaaa üòçüòç
..                                                 ...
289  @nubank poderia rolar um aumento de comemora√ß√£...
292  @rodrigo_rhr @nubank @bradesco pow, comecei co...
293                    meu cart√£o da nubank chegou üôåüôåüôå
297                     aff meu nubank novo √© mt lindo
299  @nubank o que custa me aceitar no cr√©dito? htt...

[64 rows x 1 columns]

In [11]:
lista_relevante= relevantes["Treinamento"].tolist()
lista_relevante[0]

'@rodrigo_rhr @nubank @bradesco aff, pistola estou kkk se eu estivesse devendo ou com score baixo at√© entenderia.'